 version: '3'
services:
##################### Hadoop Cluster ###################

###################### HDFS (1 NN & 2DN) 
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9010:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    ports:
      - "9864:9864"
    env_file:
      - ./hadoop.env
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    # volumes:
    #   - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    ports:
      - "9865:9864"
    env_file:
      - ./hadoop.env

################## Yarn (1 RM & 2 NM) 
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager1
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  nodemanager2:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager2
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864  resourcemanager:8088"
    env_file:
      - ./hadoop.env
#################################### Hbase cluster#########################################
  hbase-master:
    image: harisekhon/hbase:${VERSION:-latest}
    command: master
    env_file:
      - ./hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 zoo:2181"
    ports:
      - 16000:16000
      - 16010:16010
      
  hbase-regionserver-1:
    image: harisekhon/hbase:${VERSION:-latest}
    command: regionserver
    env_file:
      - ./hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region-1
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 zoo:2181 hbase-master:16010"  
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301
      
  hbase-regionserver-2:
    image: harisekhon/hbase:${VERSION:-latest}
    command: regionserver
    env_file:
      - ./hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region-2
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 zoo:2181 hbase-master:16010"    
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301
##########################################################################################################
  zookeeper:
    image: harisekhon/zookeeper:latest
    ports:
      - 2181:2181

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
